In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv')
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [2]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [3]:
for col in df.columns:
    if df[col].nunique() == 1:
        print(col, "-> only one unique value:", df[col].unique())

EmployeeCount -> only one unique value: [1]
Over18 -> only one unique value: <ArrowStringArray>
['Y']
Length: 1, dtype: str
StandardHours -> only one unique value: [80]

In [4]:
df = df.drop(columns=['EmployeeCount', 'Over18', 'StandardHours'], errors='ignore')
df.shape

(1470, 32)

In [5]:
df['EmployeeNumber'].nunique() == len(df)

True

In [6]:
categorical_cols = df.select_dtypes(include='object').columns.tolist()
numerical_cols = df.select_dtypes(include=np.number).columns.tolist()

print("Categorical columns:", categorical_cols)
print("\nNumerical columns:", numerical_cols)

Categorical columns: ['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']

Numerical columns: ['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14860\1228997232.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns.tolist()

In [7]:
df['AgeGroup'] = pd.cut(df['Age'], bins=[18,25,35,45,55,65], 
                          labels=['18-25','26-35','36-45','46-55','56-65'])
df[['Age','AgeGroup']].head()

   Age AgeGroup
0   41    36-45
1   49    46-55
2   37    36-45
3   33    26-35
4   27    26-35

In [8]:
df['SalaryBand'] = pd.cut(df['MonthlyIncome'], bins=[0,3000,6000,10000,15000,20000],
                            labels=['Low','Medium','High','Very High','Top'])
df[['MonthlyIncome','SalaryBand']].head()

   MonthlyIncome SalaryBand
0           5993     Medium
1           5130     Medium
2           2090        Low
3           2909        Low
4           3468     Medium

In [9]:
df['TenureGroup'] = pd.cut(df['YearsAtCompany'], bins=[-1,2,5,10,20,40],
                             labels=['0-2 yrs','3-5 yrs','6-10 yrs','11-20 yrs','20+ yrs'])
df[['YearsAtCompany','TenureGroup']].head()

   YearsAtCompany TenureGroup
0               6    6-10 yrs
1              10    6-10 yrs
2               0     0-2 yrs
3               8    6-10 yrs
4               2     0-2 yrs

In [10]:
df['TenureGroup'] = pd.cut(df['YearsAtCompany'], bins=[-1,2,5,10,20,40],
                             labels=['0-2 yrs','3-5 yrs','6-10 yrs','11-20 yrs','20+ yrs'])
df[['YearsAtCompany','TenureGroup']].head()

   YearsAtCompany TenureGroup
0               6    6-10 yrs
1              10    6-10 yrs
2               0     0-2 yrs
3               8    6-10 yrs
4               2     0-2 yrs

In [11]:
df.to_csv('../data/processed/hr_cleaned.csv', index=False)
print("Saved successfully!")

Saved successfully!